# v1
name: Theme CI
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - 'build/**'
      - 'README.md'
      - 'LICENSE'
    branches:
      [master, dev]
  pull_request:
    branches:
      [master, dev]
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - 'build/**'
      - 'README.md'
      - 'LICENSE'

jobs:
  ci:
    runs-on: ubuntu-latest
    env: 
      SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
      GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
      BLOB_SAS: ${{ secrets.BLOB_TOKEN }}

    steps:
    - uses: actions/checkout@v2

    - name: Setup sonarqube
      uses: warchant/setup-sonar-scanner@v1

    - name: Get Image Version
      uses: VirtoCommerce/vc-github-actions/get-image-version@dev
      id: image

    - name: SonarCloud Scan
      uses: VirtoCommerce/vc-github-actions/sonar-theme@dev

    - name: Build
      uses: VirtoCommerce/vc-github-actions/build-theme@dev

    - name: Publish
      id: publish
      uses: VirtoCommerce/vc-github-actions/publish-theme@dev

    - name: Create Release
      if: github.ref == 'refs/heads/master'
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ steps.image.outputs.tag }}
        release_name: ${{ steps.image.outputs.tag }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      if: github.ref == 'refs/heads/master'
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ${{ steps.publish.outputs.artifactPath }}
        asset_name: ${{ steps.publish.outputs.artifactName }}
        asset_content_type: application/zip